<template>
  <component :is="icons[name] || CircleIcon" aria-hidden="true" />
</template>

<script setup lang="ts">
// Ícones do Admin master: mesmos nomes de antes, agora desenhados pela Lucide,
// a mesma família e o mesmo traço do resto do painel.
import type { Component } from "vue";
import {
  ActivityIcon,
  ArrowRightIcon,
  BellIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  CircleIcon,
  CopyIcon,
  CreditCardIcon,
  CrownIcon,
  DownloadIcon,
  EllipsisVerticalIcon,
  EyeIcon,
  FileTextIcon,
  FlagIcon,
  GripVerticalIcon,
  HistoryIcon,
  HouseIcon,
  InfoIcon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  LinkIcon,
  LogOutIcon,
  MessageCircleIcon,
  MonitorIcon,
  PanelsTopLeftIcon,
  PauseIcon,
  PencilIcon,
  PlaneIcon,
  PlayIcon,
  PlusIcon,
  RotateCwIcon,
  ScaleIcon,
  SearchIcon,
  ShieldIcon,
  SmartphoneIcon,
  SparklesIcon,
  TagIcon,
  Trash2Icon,
  TrendingUpIcon,
  TriangleAlertIcon,
  Undo2Icon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  XIcon
} from "lucide-vue-next";

defineProps<{ name: string }>();

const icons: Record<string, Component> = {
  dash: LayoutDashboardIcon,
  pulse: ActivityIcon,
  users: UsersIcon,
  user: UserIcon,
  shield: ShieldIcon,
  crown: CrownIcon,
  cal: CalendarIcon,
  scale: ScaleIcon,
  trend: TrendingUpIcon,
  tag: TagIcon,
  video: VideoIcon,
  layout: PanelsTopLeftIcon,
  flag: FlagIcon,
  spark: SparklesIcon,
  plane: PlaneIcon,
  wa: MessageCircleIcon,
  bell: BellIcon,
  plus: PlusIcon,
  dl: DownloadIcon,
  search: SearchIcon,
  dots: EllipsisVerticalIcon,
  refresh: RotateCwIcon,
  x: XIcon,
  logout: LogOutIcon,
  monitor: MonitorIcon,
  phone: SmartphoneIcon,
  check: CheckIcon,
  alert: TriangleAlertIcon,
  copy: CopyIcon,
  play: PlayIcon,
  eye: EyeIcon,
  history: HistoryIcon,
  wallet: WalletIcon,
  card: CreditCardIcon,
  grip: GripVerticalIcon,
  home: HouseIcon,
  pages: FileTextIcon,
  key: KeyRoundIcon,
  edit: PencilIcon,
  trash: Trash2Icon,
  pause: PauseIcon,
  info: InfoIcon,
  undo: Undo2Icon,
  link: LinkIcon,
  upload: UploadIcon,
  arrow: ArrowRightIcon,
  chevron: ChevronDownIcon,
  "chevron-left": ChevronLeftIcon
};
</script>
