import type { VNode } from "vue";
import { h } from "vue";

/**
 * Biblioteca completa de ícones (Lucide, licença ISC). O desenho de todos os ~1.700 ícones fica num
 * arquivo à parte, carregado só quando o seletor abre ou quando uma página usa um ícone fora dos básicos.
 * Os ícones são salvos como "icon:<nome>" (ex.: "icon:plane-takeoff").
 */
export type IconNode = [string, Record<string, string | number>];

let catalog: Promise<Record<string, IconNode[]>> | null = null;
export const loadIconLibrary = () => {
  catalog ??= import("./generated/lucideIcons.json").then(mod => (mod.default || mod) as unknown as Record<string, IconNode[]>);
  return catalog;
};

export const renderIconNodes = (nodes: IconNode[]): VNode[] => nodes.map(([tag, attrs]) => h(tag, attrs));

/** Ícones mais usados, em categorias com nomes em português. */
export const ICON_CATEGORIES: { label: string; icons: { name: string; label: string }[] }[] = [
  { label: "Viagem", icons: [{ name: "plane", label: "Avião" }, { name: "plane-takeoff", label: "Decolagem" }, { name: "plane-landing", label: "Pouso" }, { name: "luggage", label: "Bagagem" }, { name: "briefcase", label: "Mala" }, { name: "backpack", label: "Mochila" }, { name: "map", label: "Mapa" }, { name: "map-pin", label: "Destino" }, { name: "map-pinned", label: "Local" }, { name: "route", label: "Roteiro" }, { name: "compass", label: "Bússola" }, { name: "globe", label: "Mundo" }, { name: "earth", label: "Terra" }, { name: "ticket", label: "Ingresso" }, { name: "tickets", label: "Ingressos" }, { name: "calendar", label: "Calendário" }, { name: "calendar-days", label: "Datas" }, { name: "calendar-check", label: "Data confirmada" }, { name: "clock", label: "Horário" }, { name: "navigation", label: "Navegação" }, { name: "milestone", label: "Marco" }, { name: "flag", label: "Bandeira" }, { name: "signpost", label: "Placa" }, { name: "camera", label: "Fotos" }, { name: "binoculars", label: "Binóculo" }, { name: "landmark", label: "Monumento" }, { name: "castle", label: "Castelo" }, { name: "church", label: "Igreja" }, { name: "ferris-wheel", label: "Parque" }, { name: "tent", label: "Camping" }, { name: "caravan", label: "Trailer" }] },
  { label: "Transporte", icons: [{ name: "bus", label: "Ônibus" }, { name: "bus-front", label: "Ônibus de frente" }, { name: "car", label: "Carro" }, { name: "car-front", label: "Carro de frente" }, { name: "car-taxi-front", label: "Táxi" }, { name: "truck", label: "Caminhão" }, { name: "train-front", label: "Trem" }, { name: "tram-front", label: "Bonde" }, { name: "ship", label: "Navio" }, { name: "sailboat", label: "Veleiro" }, { name: "anchor", label: "Âncora" }, { name: "bike", label: "Bicicleta" }, { name: "fuel", label: "Combustível" }, { name: "cable-car", label: "Teleférico" }, { name: "helicopter", label: "Helicóptero" }, { name: "rocket", label: "Foguete" }] },
  { label: "Hospedagem", icons: [{ name: "bed", label: "Cama" }, { name: "bed-double", label: "Cama de casal" }, { name: "bed-single", label: "Cama de solteiro" }, { name: "hotel", label: "Hotel" }, { name: "house", label: "Casa" }, { name: "building", label: "Prédio" }, { name: "key-round", label: "Chave" }, { name: "door-open", label: "Porta" }, { name: "bath", label: "Banheira" }, { name: "shower-head", label: "Chuveiro" }, { name: "air-vent", label: "Ar-condicionado" }, { name: "wifi", label: "Wi-Fi" }, { name: "tv", label: "TV" }, { name: "sofa", label: "Sofá" }, { name: "lamp", label: "Luminária" }, { name: "waves", label: "Piscina" }] },
  { label: "Comida", icons: [{ name: "utensils", label: "Refeições" }, { name: "utensils-crossed", label: "Restaurante" }, { name: "coffee", label: "Café" }, { name: "croissant", label: "Café da manhã" }, { name: "wine", label: "Vinho" }, { name: "beer", label: "Cerveja" }, { name: "martini", label: "Drinque" }, { name: "cup-soda", label: "Refrigerante" }, { name: "pizza", label: "Pizza" }, { name: "sandwich", label: "Lanche" }, { name: "salad", label: "Salada" }, { name: "fish", label: "Peixe" }, { name: "beef", label: "Carne" }, { name: "ice-cream-cone", label: "Sorvete" }, { name: "cake", label: "Bolo" }, { name: "cookie", label: "Biscoito" }, { name: "apple", label: "Fruta" }, { name: "chef-hat", label: "Chef" }] },
  { label: "Natureza", icons: [{ name: "mountain", label: "Montanha" }, { name: "mountain-snow", label: "Neve" }, { name: "trees", label: "Floresta" }, { name: "tree-palm", label: "Praia" }, { name: "tree-pine", label: "Pinheiro" }, { name: "leaf", label: "Folha" }, { name: "flower", label: "Flor" }, { name: "sun", label: "Sol" }, { name: "sunrise", label: "Nascer do sol" }, { name: "sunset", label: "Pôr do sol" }, { name: "moon", label: "Noite" }, { name: "cloud-sun", label: "Tempo bom" }, { name: "snowflake", label: "Floco de neve" }, { name: "umbrella", label: "Guarda-chuva" }, { name: "droplets", label: "Água" }, { name: "shell", label: "Concha" }, { name: "bird", label: "Pássaro" }, { name: "fish-symbol", label: "Mar" }, { name: "rabbit", label: "Animais" }, { name: "paw-print", label: "Pet" }] },
  { label: "Atividades", icons: [{ name: "footprints", label: "Trilha" }, { name: "person-standing", label: "Pessoa" }, { name: "bike", label: "Ciclismo" }, { name: "waves", label: "Ondas" }, { name: "music", label: "Música" }, { name: "party-popper", label: "Festa" }, { name: "drama", label: "Teatro" }, { name: "palette", label: "Arte" }, { name: "shopping-bag", label: "Compras" }, { name: "gift", label: "Presente" }, { name: "gamepad-2", label: "Jogos" }, { name: "trophy", label: "Troféu" }, { name: "medal", label: "Medalha" }, { name: "dumbbell", label: "Academia" }, { name: "heart-pulse", label: "Bem-estar" }, { name: "sparkles", label: "Experiência" }] },
  { label: "Serviços", icons: [{ name: "check", label: "Confirmado" }, { name: "circle-check", label: "Incluso" }, { name: "badge-check", label: "Verificado" }, { name: "shield-check", label: "Seguro" }, { name: "shield", label: "Proteção" }, { name: "headset", label: "Atendimento" }, { name: "headphones", label: "Áudio-guia" }, { name: "message-circle", label: "Conversa" }, { name: "phone", label: "Telefone" }, { name: "mail", label: "E-mail" }, { name: "clock", label: "Horário" }, { name: "life-buoy", label: "Suporte" }, { name: "hand-helping", label: "Ajuda" }, { name: "handshake", label: "Parceria" }, { name: "languages", label: "Idiomas" }, { name: "user-check", label: "Guia" }, { name: "users", label: "Grupo" }, { name: "baby", label: "Criança" }, { name: "accessibility", label: "Acessibilidade" }, { name: "dog", label: "Aceita pets" }, { name: "info", label: "Informação" }, { name: "star", label: "Destaque" }, { name: "heart", label: "Favorito" }, { name: "award", label: "Prêmio" }, { name: "thumbs-up", label: "Aprovado" }] },
  { label: "Pagamento", icons: [{ name: "wallet", label: "Carteira" }, { name: "credit-card", label: "Cartão" }, { name: "banknote", label: "Dinheiro" }, { name: "coins", label: "Moedas" }, { name: "piggy-bank", label: "Economia" }, { name: "dollar-sign", label: "Dólar" }, { name: "euro", label: "Euro" }, { name: "receipt", label: "Recibo" }, { name: "percent", label: "Desconto" }, { name: "tag", label: "Preço" }, { name: "badge-percent", label: "Oferta" }, { name: "hand-coins", label: "Pagamento" }, { name: "shopping-cart", label: "Carrinho" }, { name: "calculator", label: "Parcelas" }] },
  { label: "Pessoas", icons: [{ name: "user", label: "Pessoa" }, { name: "users", label: "Grupo" }, { name: "users-round", label: "Família" }, { name: "user-round", label: "Perfil" }, { name: "baby", label: "Bebê" }, { name: "smile", label: "Sorriso" }, { name: "laugh", label: "Diversão" }, { name: "heart-handshake", label: "Cuidado" }, { name: "contact", label: "Contato" }, { name: "id-card", label: "Documento" }] }
];

const LABELS = new Map(ICON_CATEGORIES.flatMap(category => category.icons.map(icon => [icon.name, icon.label] as const)));
/** Nome em português do ícone, quando ele está nas categorias. */
export const iconLabel = (name: string) => LABELS.get(name) || name.replace(/-/g, " ");
